In [5]:
# Dependencies
import glob, os
import tensorflow as tf
import pandas as pd
import numpy as np

In [17]:
path = '/Users/zhaoluyang/Downloads/Senior-Capstone-2018-2019-master/Notebooks/TestData/merge_data/4_features'                     
all_files = glob.glob(os.path.join(path, "*.csv"))     # advisable to use os.path.join as this makes concatenation OS independent

df_from_each_file = (pd.read_csv(f) for f in all_files)
concatenated_df   = pd.concat(df_from_each_file, ignore_index=True)

print("\nTraining a neural network on Iris dataset using TensorFlow ")
print("Loading the Iris data to memory...")
# Loading the dataset
# dataset = pd.read_csv('ourdata.csv')
print(concatenated_df)
print("Finish loading")


Training a neural network on Iris dataset using TensorFlow 
Loading the Iris data to memory...
           OBJID   POOLID  ATTRLENGTH      BFSIZE  HDRSIZE
0      180959341 -1000000           0   1419264.0      481
1      181053640 -1000000           0   2795520.0      491
2      181152502 -1000000           0   3388416.0      508
3      215387508 -1000000           0   4898816.0      329
4      215390564 -1000000           0  11862016.0      354
5      215393111 -1000000           0  11862016.0      353
6      215395053 -1000000           0  11862016.0      353
7      215397191 -1000000           0  11862016.0      353
8      215408700 -1000000           0   4381696.0      361
9      215422332 -1000000           0   6739968.0      368
10     216637962        4           0    697344.0      385
11     216714468        4           0    928768.0      479
12     218057161       42           0    112640.0      492
13     218092913       42           0    252928.0      515
14     218161784   

In [18]:
# One-hot encoding for the categories
norma = pd.get_dummies(concatenated_df, columns=['POOLID']) 
values = list(concatenated_dataset.columns.values)
print(concatenated_dataset)

           OBJID  ATTRLENGTH      BFSIZE  HDRSIZE  POOLID_-1000000  POOLID_-9  \
0      180959341           0   1419264.0      481                1          0   
1      181053640           0   2795520.0      491                1          0   
2      181152502           0   3388416.0      508                1          0   
3      215387508           0   4898816.0      329                1          0   
4      215390564           0  11862016.0      354                1          0   
5      215393111           0  11862016.0      353                1          0   
6      215395053           0  11862016.0      353                1          0   
7      215397191           0  11862016.0      353                1          0   
8      215408700           0   4381696.0      361                1          0   
9      215422332           0   6739968.0      368                1          0   
10     216637962           0    697344.0      385                0          0   
11     216714468           0

In [36]:
#Normalization
X_train = concatenated_dataset[values[:4]]
X_train = ((X_train - X_train.min()) / (X_train.max() - X_train.min())).fillna(0)
print(X_train)


          OBJID  ATTRLENGTH    BFSIZE   HDRSIZE
0      0.093968         0.0  0.000788  0.120415
1      0.095454         0.0  0.001552  0.127336
2      0.097012         0.0  0.001882  0.139100
3      0.636472         0.0  0.002721  0.015225
4      0.636520         0.0  0.006589  0.032526
5      0.636561         0.0  0.006589  0.031834
6      0.636591         0.0  0.006589  0.031834
7      0.636625         0.0  0.006589  0.031834
8      0.636806         0.0  0.002434  0.037370
9      0.637021         0.0  0.003744  0.042215
10     0.656176         0.0  0.000387  0.053979
11     0.657382         0.0  0.000515  0.119031
12     0.678539         0.0  0.000062  0.128028
13     0.679103         0.0  0.000140  0.143945
14     0.680188         0.0  0.000111  0.154325
15     0.681229         0.0  0.000138  0.126644
16     0.681789         0.0  0.000054  0.171626
17     0.693290         0.0  0.003136  0.110727
18     0.693303         0.0  0.001258  0.145329
19     0.693313         0.0  0.003926  0

In [37]:
#preprocess the data 
features = np.array(X_train, dtype='float32')
target = np.array(concatenated_dataset[values[4:]], dtype='float32')

# Shuffle Data
indices = np.random.choice(len(features), len(features), replace=False)
X_values = features[indices]
y_values = target[indices]

# Creating a Train and a Test Dataset
test_size = 1000
X_test = X_values[-test_size:]
X_train = X_values[:-test_size]
y_test = y_values[-test_size:]
y_train = y_values[:-test_size]

# print(X_train)
print(X_test)
# print(y_test)
# print(y_train)

[[7.0088e-01 0.0000e+00 1.1946e-04 1.0311e-01]
 [6.8010e-01 0.0000e+00 1.7919e-04 2.0000e-01]
 [7.0169e-01 0.0000e+00 2.3039e-04 8.1661e-02]
 ...
 [9.5697e-02 0.0000e+00 1.1571e-03 1.3426e-01]
 [6.9335e-01 0.0000e+00 1.8960e-03 1.4533e-01]
 [7.0257e-01 0.0000e+00 2.4854e-03 8.0969e-02]]


In [38]:
# define a neural network

# Initialize placeholders
X_data = tf.placeholder(shape=[None, 4], dtype=tf.float32)
y_target = tf.placeholder(shape=[None, 8], dtype=tf.float32)

#create seed for random_normal()
seed = 1234
np.random.seed(seed)
tf.set_random_seed(seed)

hidden_layer_nodes = 10
# We create a neural Network which contains 3 layers with 4, 8, 3 nodes repectively
w1 = tf.Variable(tf.random_normal(shape=[4,hidden_layer_nodes])) # Weight of the input layer
b1 = tf.Variable(tf.random_normal(shape=[hidden_layer_nodes]))   # Bias of the input layer
w2 = tf.Variable(tf.random_normal(shape=[hidden_layer_nodes,8])) # Weight of the hidden layer
b2 = tf.Variable(tf.random_normal(shape=[8]))                    # Bias of the hidden layer
hidden_output = tf.nn.relu(tf.add(tf.matmul(X_data, w1), b1))
final_output = tf.nn.softmax(tf.add(tf.matmul(hidden_output, w2), b2))

# Loss Function
loss = tf.reduce_mean(-tf.reduce_sum(y_target * tf.log(final_output), axis=0))

# Optimizer
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(loss)

print("A neural Network which contains 3 layers with 4, 10, 8 nodes repectively was created!")

A neural Network which contains 3 layers with 4, 10, 8 nodes repectively was created!


In [44]:
print('Training the model...')

# Interval / Epochs
interval = 100
epoch = 1000

# Initialize variables
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

# Training the model...
for i in range(1, (epoch + 1)):
    sess.run(optimizer, feed_dict={X_data: X_train, y_target: y_train})
    if i % interval == 0:
        print('Epoch', i, '|', 'Loss:', sess.run(loss, feed_dict={X_data: X_train, y_target: y_train}))

print("Training finished\n")

Training the model...
Epoch 100 | Loss: 973.0404
Epoch 200 | Loss: 841.7213
Epoch 300 | Loss: 755.81616
Epoch 400 | Loss: 659.33374
Epoch 500 | Loss: 727.3075
Epoch 600 | Loss: 814.311
Epoch 700 | Loss: 711.9629
Epoch 800 | Loss: 676.01624
Epoch 900 | Loss: 640.03534
Epoch 1000 | Loss: 509.75586
Training finished



In [45]:
# get the accuracy of the model
correct_prediction = tf.equal(tf.argmax(final_output, 1), tf.argmax(y_target,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print("The accuracy of the model is:", sess.run(accuracy, feed_dict={X_data: X_test, y_target: y_test}))

The accuracy of the model is: 0.902


In [46]:
# Prediction
np.set_printoptions(precision=4)
unknown = np.array([[0.693363, 0.0, 0.002894, 0.148097]], dtype=np.float32)
predicted = sess.run(final_output, feed_dict={X_data: unknown})
# model.predict(unknown)
print("Using model to predict pool id for features: ", unknown)
print("\nPredicted softmax vector is: ",predicted)
Class_dict={'POOLID_-1000000': 0, 'POOLID_-9': 1, 'POOLID_-1': 2, 'POOLID_4': 3, 'POOLID_-1': 4, 'POOLID_6': 5, 'POOLID_42': 6, 'POOLID_72': 7, 'POOLID_82': 8 }
pool_dict = {v:k for k,v in Class_dict.items()}
print("\nPredicted pool id is: ", pool_dict[np.argmax(predicted)])

Using model to predict pool id for features:  [[0.6934 0.     0.0029 0.1481]]

Predicted softmax vector is:  [[6.6219e-03 2.6045e-04 3.2724e-06 5.8033e-03 7.3191e-04 9.8653e-01
  8.8598e-06 4.4372e-05]]

Predicted pool id is:  POOLID_6
