In [125]:
# Dependencies
import tensorflow as tf
import pandas as pd
import numpy as np

In [130]:
print("\nTraining a neural network on Iris dataset using TensorFlow ")
print("Loading the Iris data to memory...")
# Loading the dataset
dataset = pd.read_csv('iris.csv')
print("Finish loading")


Training a neural network on Iris dataset using TensorFlow 
Loading the Iris data to memory...
Finish loading


In [131]:
# One-hot encoding for the categories
dataset = pd.get_dummies(dataset, columns=['Name']) 
values = list(dataset.columns.values)
print(dataset)

     SepalLength  SepalWidth  PetalLength  PetalWidth  Name_Iris-setosa  \
0            5.1         3.5          1.4         0.2                 1   
1            4.9         3.0          1.4         0.2                 1   
2            4.7         3.2          1.3         0.2                 1   
3            4.6         3.1          1.5         0.2                 1   
4            5.0         3.6          1.4         0.2                 1   
5            5.4         3.9          1.7         0.4                 1   
6            4.6         3.4          1.4         0.3                 1   
7            5.0         3.4          1.5         0.2                 1   
8            4.4         2.9          1.4         0.2                 1   
9            4.9         3.1          1.5         0.1                 1   
10           5.4         3.7          1.5         0.2                 1   
11           4.8         3.4          1.6         0.2                 1   
12           4.8         

In [134]:
#preprocess the data 
target = np.array(dataset[values[-3:]], dtype='float32')
features = np.array(dataset[values[0:-3]], dtype='float32')

# Shuffle Data
indices = np.random.choice(len(features), len(features), replace=False)
X_values = features[indices]
y_values = target[indices]

# Creating a Train and a Test Dataset
test_size = 30
X_test = X_values[-test_size:]
X_train = X_values[:-test_size]
y_test = y_values[-test_size:]
y_train = y_values[:-test_size]

print(X_train)
# print(X_test)
# print(y_test)
# print(y_train)

[[6.1 2.6 5.6 1.4]
 [4.9 3.1 1.5 0.1]
 [7.7 3.8 6.7 2.2]
 [5.6 3.  4.5 1.5]
 [6.4 3.2 5.3 2.3]
 [6.4 3.1 5.5 1.8]
 [5.1 3.5 1.4 0.2]
 [5.4 3.7 1.5 0.2]
 [6.7 3.  5.  1.7]
 [6.8 3.2 5.9 2.3]
 [5.5 2.6 4.4 1.2]
 [6.3 2.9 5.6 1.8]
 [5.9 3.  5.1 1.8]
 [6.3 2.8 5.1 1.5]
 [6.9 3.2 5.7 2.3]
 [6.  2.9 4.5 1.5]
 [5.8 2.7 5.1 1.9]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.1 2.3]
 [4.8 3.4 1.6 0.2]
 [7.7 2.6 6.9 2.3]
 [4.7 3.2 1.6 0.2]
 [6.4 2.8 5.6 2.2]
 [6.5 3.2 5.1 2. ]
 [6.  3.  4.8 1.8]
 [4.9 3.1 1.5 0.1]
 [6.3 3.3 6.  2.5]
 [6.3 2.7 4.9 1.8]
 [6.4 2.9 4.3 1.3]
 [5.  3.2 1.2 0.2]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [6.6 3.  4.4 1.4]
 [7.7 3.  6.1 2.3]
 [4.4 3.  1.3 0.2]
 [6.2 3.4 5.4 2.3]
 [5.  3.  1.6 0.2]
 [5.5 3.5 1.3 0.2]
 [6.  3.4 4.5 1.6]
 [7.7 2.8 6.7 2. ]
 [5.2 4.1 1.5 0.1]
 [5.5 2.4 3.8 1.1]
 [5.9 3.2 4.8 1.8]
 [4.6 3.4 1.4 0.3]
 [5.1 3.8 1.9 0.4]
 [6.  2.7 5.1 1.6]
 [6.1 2.9 4.7 1.4]
 [6.1 2.8 4.7 1.2]
 [5.1 3.4 1.5 0.2]
 [6.9 3.1 5.4 2.1]
 [6.8 3.  5.5 2.1]
 [5.  2.  3.5 1. ]
 [5.8 2.7 5.

In [138]:
# define a neural network

# Initialize placeholders
X_data = tf.placeholder(shape=[None, 4], dtype=tf.float32)
y_target = tf.placeholder(shape=[None, 3], dtype=tf.float32)

#create seed for random_normal()
seed = 1234
np.random.seed(seed)
tf.set_random_seed(seed)

hidden_layer_nodes = 8
# We create a neural Network which contains 3 layers with 4, 8, 3 nodes repectively
w1 = tf.Variable(tf.random_normal(shape=[4,hidden_layer_nodes])) # Weight of the input layer
b1 = tf.Variable(tf.random_normal(shape=[hidden_layer_nodes]))   # Bias of the input layer
w2 = tf.Variable(tf.random_normal(shape=[hidden_layer_nodes,3])) # Weight of the hidden layer
b2 = tf.Variable(tf.random_normal(shape=[3]))                    # Bias of the hidden layer
hidden_output = tf.nn.relu(tf.add(tf.matmul(X_data, w1), b1))
final_output = tf.nn.softmax(tf.add(tf.matmul(hidden_output, w2), b2))

# Loss Function
loss = tf.reduce_mean(-tf.reduce_sum(y_target * tf.log(final_output), axis=0))

# Optimizer
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(loss)

print("A neural Network which contains 3 layers with 4, 8, 3 nodes repectively was created!")

A neural Network which contains 3 layers with 4, 8, 3 nodes repectively was created!


In [139]:
print('Training the model...')

# Interval / Epochs
interval = 100
epoch = 1000

# Initialize variables
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

# Training the model...
for i in range(1, (epoch + 1)):
    sess.run(optimizer, feed_dict={X_data: X_train, y_target: y_train})
    if i % interval == 0:
        print('Epoch', i, '|', 'Loss:', sess.run(loss, feed_dict={X_data: X_train, y_target: y_train}))

print("Training finished\n")

Training the model...
Epoch 100 | Loss: 15.617526
Epoch 200 | Loss: 11.483928
Epoch 300 | Loss: 8.14018
Epoch 400 | Loss: 6.1576653
Epoch 500 | Loss: 5.3353896
Epoch 600 | Loss: 4.848772
Epoch 700 | Loss: 4.5151687
Epoch 800 | Loss: 4.273574
Epoch 900 | Loss: 4.0905156
Epoch 1000 | Loss: 3.9469602
Training finished



In [142]:
# get the accuracy of the model
correct_prediction = tf.equal(tf.argmax(final_output, 1), tf.argmax(y_target,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print("The accuracy of the model is:", sess.run(accuracy, feed_dict={X_data: X_test, y_target: y_test}))

The accuracy of the model is: 0.96666664


In [148]:
# Prediction
np.set_printoptions(precision=4)
unknown = np.array([[6.1, 3.1, 5.1, 1.1]], dtype=np.float32)
predicted = sess.run(final_output, feed_dict={X_data: unknown})
# model.predict(unknown)
print("Using model to predict species for features: ", unknown)
print("\nPredicted softmax vector is: ",predicted)
Class_dict={'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}
species_dict = {v:k for k,v in Class_dict.items()}
print("\nPredicted species is: ", species_dict[np.argmax(predicted)])

Using model to predict species for features:  [[6.1 3.1 5.1 1.1]]

Predicted softmax vector is:  [[3.7255e-04 9.4318e-01 5.6447e-02]]

Predicted species is:  Iris-versicolor
