In [1]:
# basic tensorflow tutorial
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
# import matplotlib.pyplot as plt
print(tf.__version__)

1.10.0


In [2]:
fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [3]:
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

In [4]:
train_images.shape

(60000, 28, 28)

In [5]:
len(train_labels)

60000

In [6]:
train_labels

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [7]:
test_images.shape


The history saving thread hit an unexpected error (OperationalError('disk I/O error',)).History will not be written to the database.

(10000, 28, 28)

In [8]:
len(test_labels)


10000

In [9]:
train_images = train_images / 255.0

test_images = test_images / 255.0

In [10]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])

In [11]:
model.compile(optimizer=tf.train.AdamOptimizer(), 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [12]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
60000/60000 [==============================] - 5s 81us/step - loss: 0.5042 - acc: 0.8237
Epoch 2/5
60000/60000 [==============================] - 4s 75us/step - loss: 0.3771 - acc: 0.8636
Epoch 3/5
60000/60000 [==============================] - 4s 75us/step - loss: 0.3393 - acc: 0.8747
Epoch 4/5
60000/60000 [==============================] - 4s 75us/step - loss: 0.3135 - acc: 0.8854
Epoch 5/5
60000/60000 [==============================] - 5s 77us/step - loss: 0.2959 - acc: 0.8914


In [13]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
test_acc

10000/10000 [==============================] - 0s 39us/step


0.8759

In [14]:
predictions = model.predict(test_images)

In [15]:
predictions[0]

array([5.9808241e-05, 7.8858868e-08, 8.8193224e-07, 6.8400530e-09,
       1.8459281e-05, 4.3482270e-02, 7.4183358e-06, 2.8754037e-02,
       1.5276370e-06, 9.2767555e-01], dtype=float32)

In [16]:
np.argmax(predictions[0])

9

In [17]:
test_labels[0]

9

In [18]:
img = test_images[0]
img.shape

(28, 28)

In [19]:
img = (np.expand_dims(img,0))
img.shape

(1, 28, 28)

In [20]:
predictions_single = model.predict(img)
predictions_single

array([[5.9808292e-05, 7.8859166e-08, 8.8193224e-07, 6.8400920e-09,
        1.8459297e-05, 4.3482270e-02, 7.4183495e-06, 2.8754050e-02,
        1.5276383e-06, 9.2767555e-01]], dtype=float32)

In [21]:
np.argmax(predictions_single[0])

9